### PR TITLE
David/define item uses

### PR DESCRIPTION
**Pull request by DewsDavid31**

### CODE REVIEW

**Comment by DewsDavid31** [comment]
Currently items don't interact with rooms or players, but have silly print statements and use the <item you want to use>.use(<name of thing being used>) format of call, also has repl method in place using "use <item>" format

**Review by zanguian — APPROVED** [review]
This is fine

**Comment by DewsDavid31** [comment]
@ddejohn this only adds a use command and a use method to items, will this collide with anything you have?

**Comment by DewsDavid31** [comment]
Bug has been found on runtime

**Pull request closed without merging**
